# Generated by Django 2.0.4 on 2018-05-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('eventName', models.CharField(default='Thursty Party', max_length=100)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(default='Upcoming', max_length=20)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
