# Generated by Django 2.0.4 on 2018-05-08 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Party', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='attended',
            field=models.ManyToManyField(related_name='party_attended', to='User.User'),
        ),
        migrations.AddField(
            model_name='party',
            name='hostedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostedBy', to='User.Organizer'),
        ),
        migrations.AddField(
            model_name='party',
            name='paidCash',
            field=models.ManyToManyField(related_name='party_paidCash', to='User.User'),
        ),
        migrations.AddField(
            model_name='party',
            name='paidVenmo',
            field=models.ManyToManyField(related_name='party_paidVenmo', to='User.User'),
        ),
    ]
