# Generated by Django 2.0.4 on 2018-05-11 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0002_auto_20180508_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='partyid',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='attended',
            field=models.ManyToManyField(blank=True, related_name='party_attended', to='User.User'),
        ),
        migrations.AlterField(
            model_name='party',
            name='hostedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostedBy', to='User.Organizer'),
        ),
        migrations.AlterField(
            model_name='party',
            name='paidCash',
            field=models.ManyToManyField(blank=True, related_name='party_paidCash', to='User.User'),
        ),
        migrations.AlterField(
            model_name='party',
            name='paidVenmo',
            field=models.ManyToManyField(blank=True, related_name='party_paidVenmo', to='User.User'),
        ),
    ]
