# Generated by Django 2.0.4 on 2018-05-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0002_auto_20180511_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='partyid',
            field=models.TextField(max_length=100),
        ),
    ]
