# Generated by Django 2.0.4 on 2018-05-08 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.TextField()),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('college', models.TextField(default='UCLA')),
                ('email', models.TextField()),
                ('phone', models.TextField(default='N/A')),
                ('isOperator', models.BooleanField(default=False)),
                ('isOrganizer', models.BooleanField(default=False)),
                ('universityID', models.TextField(default='N/A')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='User.User')),
                ('checkInPermissionsFor', models.ManyToManyField(related_name='operator_checkInPermissionsFor', to='Party.Party')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='User.User')),
                ('organizationName', models.TextField()),
                ('parties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Party.Party')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='attendedParties',
            field=models.ManyToManyField(related_name='user_attenededParties', to='Party.Party'),
        ),
        migrations.AddField(
            model_name='user',
            name='goingTo',
            field=models.ManyToManyField(related_name='user_goingTo', to='Party.Party'),
        ),
    ]
